version = 5.2.2
archive_dir = /etc/letsencrypt/archive/xn----btbccya0aicgcyy.xn--p1ai
cert = /etc/letsencrypt/live/xn----btbccya0aicgcyy.xn--p1ai/cert.pem
privkey = /etc/letsencrypt/live/xn----btbccya0aicgcyy.xn--p1ai/privkey.pem
chain = /etc/letsencrypt/live/xn----btbccya0aicgcyy.xn--p1ai/chain.pem
fullchain = /etc/letsencrypt/live/xn----btbccya0aicgcyy.xn--p1ai/fullchain.pem
[renewalparams]
account = 7731ed948adc63d9c422cdc8fb52f785
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
www.xn----btbccya0aicgcyy.xn--p1ai = /var/www/certbot
www.xn--80aao3ackicp.xn----btbccya0aicgcyy.xn--p1ai = /var/www/certbot
xn----btbccya0aicgcyy.xn--p1ai = /var/www/certbot
xn--80aao3ackicp.xn----btbccya0aicgcyy.xn--p1ai = /var/www/certbot
